package firok.topaz;

/**
 * CSS 用英文色彩
 *
 * @since 3.11.0
 * @author Firok
 */
@SuppressWarnings("all")
public class CssColors
{
	public static final int Black = 0x000000;
	public static final int Navy = 0x000080;
	public static final int DarkBlue = 0x00008B;
	public static final int MediumBlue = 0x0000CD;
	public static final int Blue = 0x0000FF;
	public static final int DarkGreen = 0x006400;
	public static final int Green = 0x008000;
	public static final int Teal = 0x008080;
	public static final int DarkCyan = 0x008B8B;
	public static final int DeepSkyBlue = 0x00BFFF;
	public static final int DarkTurquoise = 0x00CED1;
	public static final int MediumSpringGreen = 0x00FA9A;
	public static final int Lime = 0x00FF00;
	public static final int SpringGreen = 0x00FF7F;
	public static final int Aqua = 0x00FFFF;
	public static final int Cyan = 0x00FFFF;
	public static final int MidnightBlue = 0x191970;
	public static final int DodgerBlue = 0x1E90FF;
	public static final int LightSeaGreen = 0x20B2AA;
	public static final int ForestGreen = 0x228B22;
	public static final int SeaGreen = 0x2E8B57;
	public static final int DarkSlateGray = 0x2F4F4F;
	public static final int LimeGreen = 0x32CD32;
	public static final int MediumSeaGreen = 0x3CB371;
	public static final int Turquoise = 0x40E0D0;
	public static final int RoyalBlue = 0x4169E1;
	public static final int SteelBlue = 0x4682B4;
	public static final int DarkSlateBlue = 0x483D8B;
	public static final int MediumTurquoise = 0x48D1CC;
	public static final int Indigo = 0x4B0082;
	public static final int DarkOliveGreen = 0x556B2F;
	public static final int CadetBlue = 0x5F9EA0;
	public static final int CornflowerBlue = 0x6495ED;
	public static final int MediumAquaMarine = 0x66CDAA;
	public static final int DimGray = 0x696969;
	public static final int SlateBlue = 0x6A5ACD;
	public static final int OliveDrab = 0x6B8E23;
	public static final int SlateGray = 0x708090;
	public static final int LightSlateGray = 0x778899;
	public static final int MediumSlateBlue = 0x7B68EE;
	public static final int LawnGreen = 0x7CFC00;
	public static final int Chartreuse = 0x7FFF00;
	public static final int Aquamarine = 0x7FFFD4;
	public static final int Maroon = 0x800000;
	public static final int Purple = 0x800080;
	public static final int Olive = 0x808000;
	public static final int Gray = 0x808080;
	public static final int SkyBlue = 0x87CEEB;
	public static final int LightSkyBlue = 0x87CEFA;
	public static final int BlueViolet = 0x8A2BE2;
	public static final int DarkRed = 0x8B0000;
	public static final int DarkMagenta = 0x8B008B;
	public static final int SaddleBrown = 0x8B4513;
	public static final int DarkSeaGreen = 0x8FBC8F;
	public static final int LightGreen = 0x90EE90;
	public static final int MediumPurple = 0x9370DB;
	public static final int DarkViolet = 0x9400D3;
	public static final int PaleGreen = 0x98FB98;
	public static final int DarkOrchid = 0x9932CC;
	public static final int YellowGreen = 0x9ACD32;
	public static final int Sienna = 0xA0522D;
	public static final int Brown = 0xA52A2A;
	public static final int DarkGray = 0xA9A9A9;
	public static final int LightBlue = 0xADD8E6;
	public static final int GreenYellow = 0xADFF2F;
	public static final int PaleTurquoise = 0xAFEEEE;
	public static final int LightSteelBlue = 0xB0C4DE;
	public static final int PowderBlue = 0xB0E0E6;
	public static final int FireBrick = 0xB22222;
	public static final int DarkGoldenRod = 0xB8860B;
	public static final int MediumOrchid = 0xBA55D3;
	public static final int RosyBrown = 0xBC8F8F;
	public static final int DarkKhaki = 0xBDB76B;
	public static final int Silver = 0xC0C0C0;
	public static final int MediumVioletRed = 0xC71585;
	public static final int IndianRed   =0xCD5C5C;
	public static final int Peru = 0xCD853F;
	public static final int Chocolate = 0xD2691E;
	public static final int Tan = 0xD2B48C;
	public static final int LightGray = 0xD3D3D3;
	public static final int Thistle = 0xD8BFD8;
	public static final int Orchid = 0xDA70D6;
	public static final int GoldenRod = 0xDAA520;
	public static final int PaleVioletRed = 0xDB7093;
	public static final int Crimson = 0xDC143C;
	public static final int Gainsboro = 0xDCDCDC;
	public static final int Plum = 0xDDA0DD;
	public static final int BurlyWood = 0xDEB887;
	public static final int LightCyan = 0xE0FFFF;
	public static final int Lavender = 0xE6E6FA;
	public static final int DarkSalmon = 0xE9967A;
	public static final int Violet = 0xEE82EE;
	public static final int PaleGoldenRod = 0xEEE8AA;
	public static final int LightCoral = 0xF08080;
	public static final int Khaki = 0xF0E68C;
	public static final int AliceBlue = 0xF0F8FF;
	public static final int HoneyDew = 0xF0FFF0;
	public static final int Azure = 0xF0FFFF;
	public static final int SandyBrown = 0xF4A460;
	public static final int Wheat = 0xF5DEB3;
	public static final int Beige = 0xF5F5DC;
	public static final int WhiteSmoke = 0xF5F5F5;
	public static final int MintCream = 0xF5FFFA;
	public static final int GhostWhite = 0xF8F8FF;
	public static final int Salmon = 0xFA8072;
	public static final int AntiqueWhite = 0xFAEBD7;
	public static final int Linen = 0xFAF0E6;
	public static final int LightGoldenRodYellow = 0xFAFAD2;
	public static final int OldLace = 0xFDF5E6;
	public static final int Red = 0xFF0000;
	public static final int Fuchsia = 0xFF00FF;
	public static final int Magenta = 0xFF00FF;
	public static final int DeepPink = 0xFF1493;
	public static final int OrangeRed = 0xFF4500;
	public static final int Tomato = 0xFF6347;
	public static final int HotPink = 0xFF69B4;
	public static final int Coral = 0xFF7F50;
	public static final int DarkOrange = 0xFF8C00;
	public static final int LightSalmon = 0xFFA07A;
	public static final int Orange = 0xFFA500;
	public static final int LightPink = 0xFFB6C1;
	public static final int Pink = 0xFFC0CB;
	public static final int Gold = 0xFFD700;
	public static final int PeachPuff = 0xFFDAB9;
	public static final int NavajoWhite = 0xFFDEAD;
	public static final int Moccasin = 0xFFE4B5;
	public static final int Bisque = 0xFFE4C4;
	public static final int MistyRose = 0xFFE4E1;
	public static final int BlanchedAlmond = 0xFFEBCD;
	public static final int PapayaWhip = 0xFFEFD5;
	public static final int LavenderBlush = 0xFFF0F5;
	public static final int SeaShell = 0xFFF5EE;
	public static final int Cornsilk = 0xFFF8DC;
	public static final int LemonChiffon = 0xFFFACD;
	public static final int FloralWhite = 0xFFFAF0;
	public static final int Snow = 0xFFFAFA;
	public static final int Yellow = 0xFFFF00;
	public static final int LightYellow = 0xFFFFE0;
	public static final int Ivory = 0xFFFFF0;
	public static final int White = 0xFFFFFF;

	public static int getColorRGB(String name)
	{
		return switch (name.toLowerCase())
		{
			case "black" -> 0x000000;
			case "navy" -> 0x000080;
			case "darkblue" -> 0x00008B;
			case "mediumblue" -> 0x0000CD;
			case "blue" -> 0x0000FF;
			case "darkgreen" -> 0x006400;
			case "green" -> 0x008000;
			case "teal" -> 0x008080;
			case "darkcyan" -> 0x008B8B;
			case "deepskyblue" -> 0x00BFFF;
			case "darkturquoise" -> 0x00CED1;
			case "mediumspringgreen" -> 0x00FA9A;
			case "lime" -> 0x00FF00;
			case "springgreen" -> 0x00FF7F;
			case "aqua" -> 0x00FFFF;
			case "cyan" -> 0x00FFFF;
			case "midnightblue" -> 0x191970;
			case "dodgerblue" -> 0x1E90FF;
			case "lightseagreen" -> 0x20B2AA;
			case "forestgreen" -> 0x228B22;
			case "seagreen" -> 0x2E8B57;
			case "darkslategray" -> 0x2F4F4F;
			case "limegreen" -> 0x32CD32;
			case "mediumseagreen" -> 0x3CB371;
			case "turquoise" -> 0x40E0D0;
			case "royalblue" -> 0x4169E1;
			case "steelblue" -> 0x4682B4;
			case "darkslateblue" -> 0x483D8B;
			case "mediumturquoise" -> 0x48D1CC;
			case "indigo " -> 0x4B0082;
			case "darkolivegreen" -> 0x556B2F;
			case "cadetblue" -> 0x5F9EA0;
			case "cornflowerblue" -> 0x6495ED;
			case "mediumaquamarine" -> 0x66CDAA;
			case "dimgray" -> 0x696969;
			case "slateblue" -> 0x6A5ACD;
			case "olivedrab" -> 0x6B8E23;
			case "slategray" -> 0x708090;
			case "lightslategray" -> 0x778899;
			case "mediumslateblue" -> 0x7B68EE;
			case "lawngreen" -> 0x7CFC00;
			case "chartreuse" -> 0x7FFF00;
			case "aquamarine" -> 0x7FFFD4;
			case "maroon" -> 0x800000;
			case "purple" -> 0x800080;
			case "olive" -> 0x808000;
			case "gray" -> 0x808080;
			case "skyblue" -> 0x87CEEB;
			case "lightskyblue" -> 0x87CEFA;
			case "blueviolet" -> 0x8A2BE2;
			case "darkred" -> 0x8B0000;
			case "darkmagenta" -> 0x8B008B;
			case "saddlebrown" -> 0x8B4513;
			case "darkseagreen" -> 0x8FBC8F;
			case "lightgreen" -> 0x90EE90;
			case "mediumpurple" -> 0x9370DB;
			case "darkviolet" -> 0x9400D3;
			case "palegreen" -> 0x98FB98;
			case "darkorchid" -> 0x9932CC;
			case "yellowgreen" -> 0x9ACD32;
			case "sienna" -> 0xA0522D;
			case "brown" -> 0xA52A2A;
			case "darkgray" -> 0xA9A9A9;
			case "lightblue" -> 0xADD8E6;
			case "greenyellow" -> 0xADFF2F;
			case "paleturquoise" -> 0xAFEEEE;
			case "lightsteelblue" -> 0xB0C4DE;
			case "powderblue" -> 0xB0E0E6;
			case "firebrick" -> 0xB22222;
			case "darkgoldenrod" -> 0xB8860B;
			case "mediumorchid" -> 0xBA55D3;
			case "rosybrown" -> 0xBC8F8F;
			case "darkkhaki" -> 0xBDB76B;
			case "silver" -> 0xC0C0C0;
			case "mediumvioletred" -> 0xC71585;
			case "indianred " -> 0xCD5C5C;
			case "peru" -> 0xCD853F;
			case "chocolate" -> 0xD2691E;
			case "tan" -> 0xD2B48C;
			case "lightgray" -> 0xD3D3D3;
			case "thistle" -> 0xD8BFD8;
			case "orchid" -> 0xDA70D6;
			case "goldenrod" -> 0xDAA520;
			case "palevioletred" -> 0xDB7093;
			case "crimson" -> 0xDC143C;
			case "gainsboro" -> 0xDCDCDC;
			case "plum" -> 0xDDA0DD;
			case "burlywood" -> 0xDEB887;
			case "lightcyan" -> 0xE0FFFF;
			case "lavender" -> 0xE6E6FA;
			case "darksalmon" -> 0xE9967A;
			case "violet" -> 0xEE82EE;
			case "palegoldenrod" -> 0xEEE8AA;
			case "lightcoral" -> 0xF08080;
			case "khaki" -> 0xF0E68C;
			case "aliceblue" -> 0xF0F8FF;
			case "honeydew" -> 0xF0FFF0;
			case "azure" -> 0xF0FFFF;
			case "sandybrown" -> 0xF4A460;
			case "wheat" -> 0xF5DEB3;
			case "beige" -> 0xF5F5DC;
			case "whitesmoke" -> 0xF5F5F5;
			case "mintcream" -> 0xF5FFFA;
			case "ghostwhite" -> 0xF8F8FF;
			case "salmon" -> 0xFA8072;
			case "antiquewhite" -> 0xFAEBD7;
			case "linen" -> 0xFAF0E6;
			case "lightgoldenrodyellow" -> 0xFAFAD2;
			case "oldlace" -> 0xFDF5E6;
			case "red" -> 0xFF0000;
			case "fuchsia" -> 0xFF00FF;
			case "magenta" -> 0xFF00FF;
			case "deeppink" -> 0xFF1493;
			case "orangered" -> 0xFF4500;
			case "tomato" -> 0xFF6347;
			case "hotpink" -> 0xFF69B4;
			case "coral" -> 0xFF7F50;
			case "darkorange" -> 0xFF8C00;
			case "lightsalmon" -> 0xFFA07A;
			case "orange" -> 0xFFA500;
			case "lightpink" -> 0xFFB6C1;
			case "pink" -> 0xFFC0CB;
			case "gold" -> 0xFFD700;
			case "peachpuff" -> 0xFFDAB9;
			case "navajowhite" -> 0xFFDEAD;
			case "moccasin" -> 0xFFE4B5;
			case "bisque" -> 0xFFE4C4;
			case "mistyrose" -> 0xFFE4E1;
			case "blanchedalmond" -> 0xFFEBCD;
			case "papayawhip" -> 0xFFEFD5;
			case "lavenderblush" -> 0xFFF0F5;
			case "seashell" -> 0xFFF5EE;
			case "cornsilk" -> 0xFFF8DC;
			case "lemonchiffon" -> 0xFFFACD;
			case "floralwhite" -> 0xFFFAF0;
			case "snow" -> 0xFFFAFA;
			case "yellow" -> 0xFFFF00;
			case "lightyellow" -> 0xFFFFE0;
			case "ivory" -> 0xFFFFF0;
			case "white" -> 0xFFFFFF;
			default -> 0x000000;
		};
	}
}
